# Generated by Django 6.0.3 on 2026-04-07 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=1000)),
                ('brand_loga', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('brand_countr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100, unique=True)),
                ('car_year', models.DateField(blank=True, null=True)),
                ('car_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('car_color', models.CharField(max_length=100)),
                ('car_description', models.TextField(blank=True, null=True)),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('create_car', models.DateTimeField(auto_now_add=True)),
                ('update_car', models.DateTimeField(auto_now=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.model', verbose_name='Mashina modeli')),
            ],
        ),
    ]
