# Generated by Django 6.0.3 on 2026-04-07 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Cars',
        ),
        migrations.RenameModel(
            old_name='Model',
            new_name='Models',
        ),
    ]
